# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- about         # See also: `about_content`
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
  <p>Etiam porta <em>sem malesuada magna</em> mollis euismod.
  Cras mattis consectetur purus sit amet fermentum. Aenean
  lacinia bibendum nulla sed consectetur.</p>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
# DOC:
  # https://business.twitter.com/en/help/campaign-setup/campaign-targeting/tailored-audiences-from-web.html
# EXAMPLE: twitter_pixel_id: 'xx11x'
twitter_pixel_id:
# EXAMPLE: twitter_std_event: 'PageView'
twitter_std_event:
favicon:
twitter_id:
google_plus:
fb_admins:
fb_app_id:
disqus_sitename:
twitter:
instagram:
github:
